GET http://localhost:8080/turmas HTTP/1.1
Authorization: Basic am9hb0B0ZXN0ZS5jb206QUJDMTIz
###

POST http://localhost:8080/turmas HTTP/1.1
Content-Type: application/json

{
    "codigo" : "T001",
    "nomeDisciplina" : "Processamento de Linguagem",
    "semestre" : 2,
    "ano" : 2026
}


###

POST http://localhost:8080/turmas HTTP/1.1
Content-Type: application/json

{
  "codigo" : "T01",
  "nomeDisciplina" : "Laboratório de Desenvolvimento",
  "semestre" : 2,
  "ano" : 2026
}

###

DELETE http://localhost:8080/turmas/3 HTTP/1.1


###

PUT http://localhost:8080/turmas/3 HTTP/1.1
Content-Type: application/json

{
  "id" : 1,
  "codigo" : "T003",
  "nomeDisciplina" : "Matematica",
  "semestre" : 2,
  "ano" : 2026
}